### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by pdruley** [rockset/terraform-provider-rockset#31]
https://github.com/rockset/terraform-provider-rockset/blob/22a5907a122f1cbb5bad3e65cc99c85dde9544f8/example.tf#L19

change univerally -> universally on line 19 and 20.

**Comment by pdruley** [comment]
I saw a couple other examples of this misspelling, we might want to search the whole repo.

**Comment by pmenglund** [comment]
fixed in #40
