### ISSUE TITLE
Query parameters can't be removed after they've been created

### ISSUE THREAD

**Issue by zack-klein** [rockset/terraform-provider-rockset#55]
Hello!  Noticed a bug where query parameters can't be removed from query lambdas after they've been created.

Steps to repro:
- Create a QL with 2 parameters (a and b)
- Remove parameter a
- Run apply

Expected behavior:
- Only parameter b should exist

Actual behavior:
- Both parameters a and b still exist

Additional info:
- Terraform version: `1.3.5`
- Rockset provider version: `provider registry.terraform.io/rockset/rockset v0.6.2`

Let me know if there's anything else I can do.  Thanks!

**Comment by pmenglund** [comment]
@zack-klein did you refresh the console after the `terraform apply`?

I'm using this config to rely to reproduce your issue:
```
terraform {
  required_providers {
    rockset = {
      source = "rockset/rockset"
      version = "0.6.2"
    }
  }
}

resource "rockset_workspace" "bug" {
  name = "issue55"
}

resource "rockset_query_lambda" "bug" {
  name      = "issue55"
  workspace = rockset_workspace.bug.name
  sql {
    query = "SELECT * FROM commons._events AS e WHERE e.kind = :kind"
#    query = "SELECT * FROM commons._events AS e WHERE e.kind = :kind AND e.type = :type"
    default_parameter {
      name  = "kind"
      type  = "String"
      value = "QUERY"
    }
#    default_parameter {
#      name  = "type"
#      type  = "String"
#      value = "ERROR"
#    }
  }
}
```
(this is after the second `terraform apply`) as you can see the second parameter is commented out)

The console didn't reflect the change until I forced a refresh, and a `terraform plan` shows that there are no changes to be made.

**Comment by pmenglund** [comment]
Closing as the issue lies in the console refresh rate of the query lambda.
